### ISSUE TITLE
svg파일이 build 과정에서 제대로 처리되지 않음

### ISSUE THREAD

**Issue by paulsoh** [seultt/beagleFDS#45]
https://github.com/facebookincubator/create-react-app/issues/2065
비슷한 문제를 겪는 사람이 있네요 

일단 문제가 되는 이유를 보면:
1. build/static/media 내에 똑같은 이름의 svg 파일들이 뒤의 hash만 다른 상태로 두개 씩 생성됨
2. 두 개 중에서 잘못 생성된 svg  (`module.exports = ... `) 를 실제 build에서 사용을 하려고 함 (asset-manifest.json를 보면)
3. webpack.config를 보면 svg 확장자를 로딩하는 것은 file-loader의 담당이라는 것을 알 수 있음
4. 근데 파일이 두개씩 생성되는거 보면 file-loader외에서 혹은 file-loader가 두번(? 이게 가능한지 모르겠지만) svg를 옮기려고 하는 것 같음
4. 그래서 그냥 *.svg를 file-loader 말고 url-loader로 쓰게끔 바꿔봤는데 svg파일이 제대로 로딩되지 않는 문제는 해결됨
5. file-loader와 url-loader는 역할은 거의 비슷한데 용량이 작은 file의 경우(대부분의 svg파일들) 외부 파일로 관리하는 게 아니라(귀찮, 별도 api 요청, 비쌈) 그냥 인라인으로 svg파일을 관리할 수 있도록(별도 요청 없이 인라인에 svg파일이 있으니 좀 더 효율) 해주는 차이가 있음

왜 이런 에러가 생겼는지는 모르겠지만! 일단 이런 식으로 해결은 가능한 것 같네요.

**Comment by gigantes88** [comment]
webpack을 잘몰라서 못하고 있다가 오늘에서야 해결했습니다. 감사합니다.

```js
// webpack.config.dev.js, webpack.config.prod.js
...
          {
            test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/, /\.svg$/],
            loader: require.resolve('url-loader'),
            options: {
              limit: 10000,
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
...
          {
            exclude: [
              /\.html$/,
              /\.(js|jsx)$/,
              /\.css$/,
              /\.json$/,
              /\.bmp$/,
              /\.gif$/,
              /\.jpe?g$/,
              /\.png$/,
              /\.scss$/, // 여기 추가
              /\.svg$/,
            ],
            loader: require.resolve('file-loader'),
            options: {
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
...
```
