### ISSUE TITLE
Header Component내 오타 발견

### ISSUE THREAD

**Issue by paulsoh** [seultt/beagleFDS#6]
beagleFDS/src/components/header/header.js 내 constructor를 보면 props를 인자로 받아야되는데 그냥 호출되어있네요!

```
constructor(props) {
  super(props)
}
```

위와 같은 식으로 해줘야 Header가 상위 Component로 부터 props를 받게 되거든 제대로 받을 수 있게 됩니다!

**Comment by seultt** [comment]
넵!! 감사합니다 👍

**Comment by paulsoh** [comment]
조치가 되셨으면 해당 이슈 닫으시면 됩니다!
